# Compatibilidade temporária durante a migração incremental para src layout.
from financeirane.config import (
    AMBIENTES_PERMITIDOS,
    APP_ENV,
    AUTHORIZED_CHAT_IDS,
    AUTHORIZED_CHAT_IDS_RAW,
    CATEGORIAS_PERMITIDAS,
    FORMAS_PAGAMENTO_PERMITIDAS,
    GEMINI_API_KEY,
    GOOGLE_CREDENTIALS_FILE,
    MAX_MESSAGE_LENGTH,
    MAX_PARCELAS,
    SPREADSHEET_ID,
    SPREADSHEET_NAME,
    TELEGRAM_TOKEN,
    TIPOS_PERMITIDOS,
    parse_authorized_chat_ids,
    validate_required_settings,
)

__all__ = [
    "AUTHORIZED_CHAT_IDS",
    "AMBIENTES_PERMITIDOS",
    "APP_ENV",
    "AUTHORIZED_CHAT_IDS_RAW",
    "CATEGORIAS_PERMITIDAS",
    "FORMAS_PAGAMENTO_PERMITIDAS",
    "GEMINI_API_KEY",
    "GOOGLE_CREDENTIALS_FILE",
    "MAX_MESSAGE_LENGTH",
    "MAX_PARCELAS",
    "SPREADSHEET_ID",
    "SPREADSHEET_NAME",
    "TELEGRAM_TOKEN",
    "TIPOS_PERMITIDOS",
    "parse_authorized_chat_ids",
    "validate_required_settings",
]
